kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow_app1
  namespace: data1
spec:
  podSelector:
  ingress:
  - ports:
    - port: 3306
    from:
      - namespaceSelector:
          matchLabels:
            name: app1